packages:
  - apps/web
  - packages/*

catalog:
  typescript: ^5.7.2

catalogs:
  next:
    "next": "15.1.0"
    "eslint-config-next": "15.1.0"

  react:
    "react": "^19.0.0"
    "react-dom": "^19.0.0"
    "@types/react": "^19"
    "@types/react-dom": "^19"

  tailwindcss:
    "tailwindcss": "4.0.0-beta.6"
    "@tailwindcss/postcss": "4.0.0-beta.6"
    "postcss": "^8.4"
