import type React from "react";
import type { Metadata } from "next";
import * as Layout from "@/components/layout";
import Sidebar from "@/components/sidebar";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Patchwork",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-white antialiased">
      <body className="h-full">
        <Layout.Root>
          <Layout.Sidebar>
            <Sidebar />
          </Layout.Sidebar>
          <Layout.View>{children}</Layout.View>
        </Layout.Root>
      </body>
    </html>
  );
}
